# Configuration for https://travis-ci.org/

sudo: required
# Ubuntu 14.04 Trusty support (for C++11-enabled compilers):
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - libfftw3-dev
    - libjack-jackd2-dev
    - portaudio19-dev
    - libsndfile1-dev
    - puredata-dev
    # For Ubuntu 12.04 Precise Pangolin:
    #- octave3.2-headers
    # For later Ubuntu (and Debian) versions:
    - liboctave-dev
before_install:
  - git clone https://github.com/grrrr/flext.git
  - cd flext
  - ./build.sh pd gcc || true
  - ./build.sh pd gcc || true
  - ./build.sh pd gcc
  - sudo ./build.sh pd gcc install
  - cd ..
script:
  - make -C unit_tests
  - make -C performance_tests
  - make -C examples
  - make -C examples mex
  - make -C examples mex-double
  - make -C examples pd FLEXTPATH=../flext
