name: Build Pd Externals for macOS
on: [push, pull_request]
jobs:
  pd-darwin:
    runs-on: macos-latest
    steps:
      - name: install macOS packages
        run: |
          brew cask install pd
      - name: checkout flext
        uses: actions/checkout@v2
        with:
          repository:  grrrr/flext
          path: flext
      - name: build and install flext
        working-directory: flext
        run: |
          ./build.sh pd gcc || true
          PD_APP=$(ls -d /Applications/Pd-*.app)
          echo "PDPATH=$PD_APP/Contents/Resources" >> buildsys/config-mac-pd-gcc.txt
          ./build.sh pd gcc || true
          ./build.sh pd gcc
          sudo ./build.sh pd gcc install
      - name: checkout APF source code
        uses: actions/checkout@v2
        with:
          path: apf
      - name: build Pd externals
        working-directory: apf/examples
        run: |
          make pd FLEXTPATH="$GITHUB_WORKSPACE/flext"
